### ISSUE TITLE
binary for amd64 in linux arm64 image

### ISSUE THREAD

**Issue by ezxfv** [cilium/tetragon#1163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

exec /usr/bin/tetragon-operator: exec format error

### Tetragon Version

quay.io/cilium/tetragon-operator:v0.9.0

### Kernel Version

Linux x 5.15.0-75-generic #82-Ubuntu SMP Mon Jun 12 06:02:05 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

1.27

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mtardy** [comment]
Hey indeed, `v0.9.0` has this issue and it was already fixed by https://github.com/cilium/tetragon/pull/880 but we did not make any further releases yet. If you want to run Tetragon on arm64, I would suggest using the images that are built on top of main or using the `v0.10.0-pre` tags https://quay.io/repository/cilium/tetragon-operator?tab=tags&tag=latest, with the according Tetragon image.

**Comment by mtardy** [comment]
As this specific bug has already been fixed, I'll close this issue. Please comment again or reopen if you don't agree.
