### ISSUE TITLE
allow event filtering based on tracing policy

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#1855]
That is,  enable filtering based on the tracing policy name in https://github.com/cilium/tetragon/tree/main/pkg/filters

**Comment by kkourt** [comment]
> Hi @kkourt,
> 
> I have just deployed Tetragon in a `kind` cluster for the first time and have started exploring the docs and codebase around it.

Cool!
> 
> I have a WIP branch in my fork to deal with this issue and improve the docs. LMK if proposed changes are in the right direction:
> 
> https://github.com/ioandr/tetragon/commits/feature-i-filter-policies
> 
> Note that I haven't started testing the code yet.

From a quick look the changes seem to be in the right direction. Feel free to create a separate PR with the documentation changes. Would love to get those merged! Thannks!

**Comment by ioandr** [comment]
So, I allocated some more time into this and now have the following:

1. I deployed a tracing policy and saw events like the one below:

   ```json
    {
        "process_kprobe": {
        "process": {
            ...
        },
        "parent": {
            ...
        },
        "function_name": "security_file_permission",
        "args": [
            ...
        ],
        "return": {
            "int_arg": 0
        },
        "action": "KPROBE_ACTION_POST",
        "policy_name": "file-monitoring-filtered"
        },
        "node_name": "kind-control-plane",
        "time": "2023-12-10T22:10:19.356441099Z"
    }
   ```

   From the above JSON structure I understand that we need to extract the value of the `process_kprobe.policy_name` field of the event in order to do the filtering based on the name of the tracing policy.

2. First, I took a look the [generateResponseGetProcess()](https://github.com/cilium/tetragon/blob/main/cmd/protoc-gen-go-tetragon/helpers/helpers.go#L55) and [generateResponseGetParent()](https://github.com/cilium/tetragon/blob/main/cmd/protoc-gen-go-tetragon/helpers/helpers.go#L113) generator functions, even though the `process` and `parent` event fields are not top-level ones like the `process_kprobe` one we care about. These functions work with the v1 API's [GetEventsResponse](https://github.com/cilium/tetragon/tree/main/api/v1#tetragon-GetEventsResponse).

3. Then, after looking a bit the API, I found out that to retrieve the process kprobe we can probably take advantage of the v1 API's [GetProcessKprobe()](https://github.com/cilium/tetragon/blob/main/api/v1/tetragon/events.pb.go#L672) function which returns an event's `ProcessKprobe` struct (if present) that, in turn, contains a `PolicyName` string field.

4. Based on the above, I implemented a `generateResponseGetProcessKprobe()` generator function that generates the `ResponseGetProcessKprobe()` helper function that returns a pointer to a `tetragon.ProcessKprobe` struct. 

### Questions

- Do you agree with this approach? Feel free to propose an alternative if this is not what you have in mind
- Do we have to perform any filtering on events similar to [isProcessEvent()](https://github.com/cilium/tetragon/blob/main/cmd/protoc-gen-go-tetragon/common/common.go#L141), [isParentEvent()](https://github.com/cilium/tetragon/blob/main/cmd/protoc-gen-go-tetragon/common/common.go#L146)
- Do we have to check for specific event types before calling `response.GetProcessKprobe()`?
- What is the difference between a response and an event?

I will open a WIP PR that I will start testing soon if the above make sense.

**Comment by ioandr** [comment]
Quick update here:

1. I added tests for the policy name filter
2. I marked the PR as ready for review

Feel free to comment if proposed changes make sense :)
