### ISSUE TITLE
Proposal: replace perf map to a ring buffer

### ISSUE THREAD

**Issue by Forsworns** [cilium/tetragon#208]
Currently Tetragon uses `tcpmon_map` to send perf events, which is `BPF_MAP_TYPE_PERF_EVENT_ARRAY`. 

Is it better to replace it by `BPF_MAP_TYPE_RINGBUF`? 

See the blog on [ringbuf vs perfbuf](https://nakryiko.com/posts/bpf-ringbuf/).

___

BTW, why the size of `tcpmon_map` is not set?

https://github.com/cilium/tetragon/blob/735c3dd6dba5b7a068cf29cd37d603cb8c0c2058/bpf/lib/hubble_msg.h#L21

**Comment by kkourt** [comment]
> Is it better to replace it by BPF_MAP_TYPE_RINGBUF?

The issue with using `BPF_MAP_TYPE_RINGBUF` is that it is only support in >= 5.8 kernels. Because tetragon is also required to work on older kernels, we cannot just replace  `BPF_MAP_TYPE_PERF_EVENT_ARRAY` with `BPF_MAP_TYPE_RINGBUF`, and we would need to support both which would complicate the code and increase maintenance burden.
